### ISSUE TITLE
Not able to get the prediction for Test.csv

### ISSUE THREAD

**Issue by vikasgoel2000** [uf-hobi-informatics-lab/ClinicalTransformerRelationExtraction#23]
Hi 

I am just trying to run the code to get the predictions for the test.csv. i am trying with the pre trained model at https://transformer-models.s3.amazonaws.com/mimiciii_bert_10e_128b.zip.

While running code I am getting an error as AttributeError: 'BertConfig' object has no attribute 'tags'

Screen shot of my scree is as below 

![image](https://user-images.githubusercontent.com/7195390/162722872-6ee11ad7-19ce-4cb2-bfea-b03e7ae67ee3.png)

**Comment by bugface** [comment]
the pretrained model is pretrained on MLM, not on RE so it is not an out-of-box RE model for inference.  

You need to first train a RE model on training data during which the tags and other configs will be generated based on the dataset and parameters, then you can run inference.
